### ISSUE TITLE
Не обновляется 

### ISSUE THREAD

**Issue by CurikovMF** [efa2000/node-red-contrib-alice#31]
При обновлении через менеджер паллет выдает ошибку 

Node-red  установлен в докере аддоном к НА 

2020-07-02T04:54:52.510Z Install : node-red-contrib-alice 0.3.13

2020-07-02T04:56:01.913Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-alice@0.3.13
2020-07-02T04:58:25.847Z [out] 
2020-07-02T04:58:25.847Z [out] > grpc@1.24.2 install /config/node-red/node_modules/grpc
2020-07-02T04:58:25.847Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2020-07-02T04:58:25.847Z [out] 
2020-07-02T04:58:29.703Z [err] node-pre-gyp
2020-07-02T04:58:29.709Z [err]  
2020-07-02T04:58:29.711Z [err] WARN Using request for node-pre-gyp https download 
2020-07-02T04:58:31.211Z [err] node-pre-gyp
2020-07-02T04:58:31.212Z [err]  WARN 
2020-07-02T04:58:31.213Z [err] Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-linux-arm-musl.tar.gz 
2020-07-02T04:58:31.213Z [err] node-pre-gyp WARN
2020-07-02T04:58:31.214Z [err]  Pre-built binaries not found for grpc@1.24.2 and node@12.15.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-07-02T04:58:41.019Z [err] gyp
2020-07-02T04:58:41.025Z [err]  
2020-07-02T04:58:41.026Z [err] ERR! build error 
2020-07-02T04:58:41.031Z [err] gyp
2020-07-02T04:58:41.032Z [err]  ERR! stack
2020-07-02T04:58:41.033Z [err]  Error: not found: make
2020-07-02T04:58:41.033Z [err] gyp ERR! stack
2020-07-02T04:58:41.034Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-07-02T04:58:41.034Z [err] gyp ERR! 
2020-07-02T04:58:41.035Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-07-02T04:58:41.035Z [err] gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-07-02T04:58:41.035Z [err] gyp
2020-07-02T04:58:41.036Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-07-02T04:58:41.036Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-07-02T04:58:41.037Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-07-02T04:58:41.037Z [err] gyp ERR!
2020-07-02T04:58:41.038Z [err]  stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-07-02T04:58:41.039Z [err] gyp
2020-07-02T04:58:41.040Z [err]  ERR! System Linux 4.19.108-v7+
2020-07-02T04:58:41.040Z [err] gyp 
2020-07-02T04:58:41.041Z [err] ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-07-02T04:58:41.041Z [err] gyp ERR! 
2020-07-02T04:58:41.042Z [err] cwd /config/node-red/node_modules/grpc
2020-07-02T04:58:41.042Z [err] gyp
2020-07-02T04:58:41.042Z [err]  ERR! node -v v12.15.0
2020-07-02T04:58:41.043Z [err] gyp ERR! node-gyp -v
2020-07-02T04:58:41.043Z [err]  v5.0.5
2020-07-02T04:58:41.043Z [err] gyp ERR!
2020-07-02T04:58:41.044Z [err]  not ok 
2020-07-02T04:58:41.059Z [err] node-pre-gyp
2020-07-02T04:58:41.060Z [err]  ERR! 
2020-07-02T04:58:41.060Z [err] build error 
2020-07-02T04:58:41.065Z [err] node-pre-gyp
2020-07-02T04:58:41.066Z [err]  ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-02T04:58:41.066Z [err] node-pre-gyp
2020-07-02T04:58:41.066Z [err]  ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-07-02T04:58:41.067Z [err] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
2020-07-02T04:58:41.067Z [err] node-pre-gyp ERR! 
2020-07-02T04:58:41.068Z [err] stack     at maybeClose (internal/child_process.js:1021:16)
2020-07-02T04:58:41.068Z [err] node-pre-gyp 
2020-07-02T04:58:41.068Z [err] ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-07-02T04:58:41.076Z [err] node-pre-gyp ERR! System Linux 4.19.108-v7+
2020-07-02T04:58:41.076Z [err] node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
2020-07-02T04:58:41.076Z [err] node-pre-gyp ERR! cwd /config/node-red/node_modules/grpc
2020-07-02T04:58:41.076Z [err] node-pre-gyp ERR! node -v v12.15.0
2020-07-02T04:58:41.076Z [err] node-pre-gyp ERR! node-pre-gyp -v v0.14.0
2020-07-02T04:58:41.076Z [err] node-pre-gyp ERR! not ok 
2020-07-02T04:58:41.079Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-02T04:58:49.903Z [err] npm
2020-07-02T04:58:49.904Z [err]  
2020-07-02T04:58:49.905Z [err] ERR! code ELIFECYCLE
2020-07-02T04:58:49.906Z [err] npm ERR! 
2020-07-02T04:58:49.906Z [err] errno 1
2020-07-02T04:58:49.917Z [err] npm
2020-07-02T04:58:49.918Z [err]  ERR! grpc@1.24.2 install: node-pre-gyp install --fallback-to-build --library=static_library
2020-07-02T04:58:49.918Z [err] npm ERR!
2020-07-02T04:58:49.918Z [err]  Exit status 1
2020-07-02T04:58:49.918Z [err] npm
2020-07-02T04:58:49.919Z [err]  ERR! 
2020-07-02T04:58:49.919Z [err] npm
2020-07-02T04:58:49.919Z [err]  ERR! Failed at the grpc@1.24.2 install script.
2020-07-02T04:58:49.919Z [err] npm
2020-07-02T04:58:49.920Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-07-02T04:58:50.152Z [err] 
2020-07-02T04:58:50.153Z [err] npm ERR! A complete log of this run can be found in:
2020-07-02T04:58:50.154Z [err] npm ERR!
2020-07-02T04:58:50.154Z [err]      /root/.npm/_logs/2020-07-02T04_58_50_045Z-debug.log
2020-07-02T04:58:50.267Z rc=1

**Comment by efa2000** [comment]
попробуйте установить модуль node-pre-gyp, лучше глобально 

`npm install -g node-pre-gyp
`

**Comment by CurikovMF** [comment]
установил 
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/node-pre-gyp -> /usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
+ node-pre-gyp@0.15.0
added 66 packages from 25 contributors in 30.69s

та же ситуация 
2020-07-03T10:19:25.930Z Install : node-red-contrib-alice 0.3.13

2020-07-03T10:20:36.785Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-alice@0.3.13
2020-07-03T10:25:08.684Z [out] 
2020-07-03T10:25:08.684Z [out] > grpc@1.24.2 install /config/node-red/node_modules/grpc
2020-07-03T10:25:08.684Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2020-07-03T10:25:08.684Z [out] 
2020-07-03T10:25:12.939Z [err] node-pre-gyp
2020-07-03T10:25:12.946Z [err]  
2020-07-03T10:25:12.947Z [err] WARN
2020-07-03T10:25:12.947Z [err]  Using request for node-pre-gyp https download 
2020-07-03T10:25:14.531Z [err] node-pre-gyp
2020-07-03T10:25:14.532Z [err]  WARN
2020-07-03T10:25:14.533Z [err]  Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-linux-arm-musl.tar.gz
2020-07-03T10:25:14.534Z [err]  
2020-07-03T10:25:14.534Z [err] node-pre-gyp WARN 
2020-07-03T10:25:14.535Z [err] Pre-built binaries not found for grpc@1.24.2 and node@12.15.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-07-03T10:25:27.985Z [err] gyp
2020-07-03T10:25:27.992Z [err]  
2020-07-03T10:25:27.993Z [err] ERR!
2020-07-03T10:25:27.993Z [err]  
2020-07-03T10:25:27.994Z [err] build error
2020-07-03T10:25:27.995Z [err]  
2020-07-03T10:25:28.006Z [err] gyp
2020-07-03T10:25:28.007Z [err]  
2020-07-03T10:25:28.008Z [err] ERR!
2020-07-03T10:25:28.009Z [err]  
2020-07-03T10:25:28.010Z [err] stack
2020-07-03T10:25:28.010Z [err]  Error: not found: make
2020-07-03T10:25:28.011Z [err] gyp
2020-07-03T10:25:28.012Z [err]  
2020-07-03T10:25:28.012Z [err] ERR!
2020-07-03T10:25:28.013Z [err]  
2020-07-03T10:25:28.013Z [err] stack
2020-07-03T10:25:28.014Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-07-03T10:25:28.014Z [err] gyp
2020-07-03T10:25:28.015Z [err]  
2020-07-03T10:25:28.015Z [err] ERR!
2020-07-03T10:25:28.016Z [err]  
2020-07-03T10:25:28.016Z [err] stack
2020-07-03T10:25:28.017Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-07-03T10:25:28.017Z [err] gyp
2020-07-03T10:25:28.018Z [err]  
2020-07-03T10:25:28.018Z [err] ERR!
2020-07-03T10:25:28.019Z [err]  
2020-07-03T10:25:28.019Z [err] stack
2020-07-03T10:25:28.020Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-07-03T10:25:28.020Z [err] gyp
2020-07-03T10:25:28.021Z [err]  
2020-07-03T10:25:28.021Z [err] ERR!
2020-07-03T10:25:28.022Z [err]  
2020-07-03T10:25:28.022Z [err] stack
2020-07-03T10:25:28.023Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-07-03T10:25:28.023Z [err] gyp
2020-07-03T10:25:28.023Z [err]  
2020-07-03T10:25:28.024Z [err] ERR!
2020-07-03T10:25:28.024Z [err]  
2020-07-03T10:25:28.025Z [err] stack
2020-07-03T10:25:28.025Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-07-03T10:25:28.026Z [err] gyp
2020-07-03T10:25:28.026Z [err]  
2020-07-03T10:25:28.026Z [err] ERR!
2020-07-03T10:25:28.027Z [err]  
2020-07-03T10:25:28.027Z [err] stack
2020-07-03T10:25:28.028Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-07-03T10:25:28.028Z [err] gyp
2020-07-03T10:25:28.029Z [err]  
2020-07-03T10:25:28.029Z [err] ERR!
2020-07-03T10:25:28.030Z [err]  
2020-07-03T10:25:28.031Z [err] stack
2020-07-03T10:25:28.031Z [err]      at FSReqCallback.oncomplete (fs.js:158:21)
2020-07-03T10:25:28.033Z [err] gyp
2020-07-03T10:25:28.034Z [err]  
2020-07-03T10:25:28.034Z [err] ERR! System
2020-07-03T10:25:28.035Z [err]  Linux 4.19.108-v7+
2020-07-03T10:25:28.038Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-07-03T10:25:28.038Z [err] gyp ERR! cwd /config/node-red/node_modules/grpc
2020-07-03T10:25:28.038Z [err] gyp ERR! node -v v12.15.0
2020-07-03T10:25:28.039Z [err] gyp 
2020-07-03T10:25:28.039Z [err] ERR! node-gyp -v
2020-07-03T10:25:28.039Z [err]  v5.0.5
2020-07-03T10:25:28.039Z [err] gyp 
2020-07-03T10:25:28.040Z [err] ERR! 
2020-07-03T10:25:28.040Z [err] not ok 
2020-07-03T10:25:28.060Z [err] node-pre-gyp ERR! build error 
2020-07-03T10:25:28.066Z [err] node-pre-gyp
2020-07-03T10:25:28.066Z [err]  ERR! stack
2020-07-03T10:25:28.066Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-03T10:25:28.066Z [err] node-pre-gyp 
2020-07-03T10:25:28.067Z [err] ERR! 
2020-07-03T10:25:28.067Z [err] stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-07-03T10:25:28.074Z [err] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
2020-07-03T10:25:28.074Z [err] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
2020-07-03T10:25:28.074Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-07-03T10:25:28.074Z [err] node-pre-gyp ERR! System Linux 4.19.108-v7+
2020-07-03T10:25:28.074Z [err] node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
2020-07-03T10:25:28.074Z [err] node-pre-gyp ERR!
2020-07-03T10:25:28.076Z [err]  cwd /config/node-red/node_modules/grpc
2020-07-03T10:25:28.076Z [err] node-pre-gyp ERR! node -v v12.15.0
2020-07-03T10:25:28.076Z [err] node-pre-gyp ERR! node-pre-gyp -v
2020-07-03T10:25:28.076Z [err]  v0.14.0
2020-07-03T10:25:28.076Z [err] node-pre-gyp ERR! 
2020-07-03T10:25:28.077Z [err] not ok 
2020-07-03T10:25:28.081Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-03T10:25:38.874Z [err] npm
2020-07-03T10:25:38.875Z [err]  ERR! code
2020-07-03T10:25:38.875Z [err]  ELIFECYCLE
2020-07-03T10:25:38.876Z [err] npm 
2020-07-03T10:25:38.876Z [err] ERR! 
2020-07-03T10:25:38.876Z [err] errno 1
2020-07-03T10:25:38.887Z [err] npm
2020-07-03T10:25:38.887Z [err]  ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2020-07-03T10:25:38.887Z [err] npm ERR!
2020-07-03T10:25:38.888Z [err]  Exit status 1
2020-07-03T10:25:38.888Z [err] npm
2020-07-03T10:25:38.888Z [err]  ERR!
2020-07-03T10:25:38.888Z [err]  
2020-07-03T10:25:38.888Z [err] npm 
2020-07-03T10:25:38.889Z [err] ERR!
2020-07-03T10:25:38.889Z [err]  Failed at the grpc@1.24.2 install script.
2020-07-03T10:25:38.889Z [err] npm
2020-07-03T10:25:38.889Z [err]  ERR!
2020-07-03T10:25:38.889Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-07-03T10:25:39.100Z [err] 
2020-07-03T10:25:39.101Z [err] npm 
2020-07-03T10:25:39.101Z [err] ERR! A complete log of this run can be found in:
2020-07-03T10:25:39.101Z [err] npm 
2020-07-03T10:25:39.101Z [err] ERR!
2020-07-03T10:25:39.102Z [err]      /root/.npm/_logs/2020-07-03T10_25_39_027Z-debug.log
2020-07-03T10:25:39.254Z rc=1

**Comment by efa2000** [comment]
меня смущает, что у вас стоит старая версия node-js v10
> npm WARN npm npm does not support Node.js v10.19.0

попробуйте обновить node до 12-ой версии 
если у вас debian 
`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs`

подробнее по инсталляции Node можно здесь  https://github.com/nodesource/distributions/blob/master/README.md#debinstall

и попробуйте установить заново модуль

**Comment by KuzinHouse** [comment]
Та же проблема Но не инсталлируется.

**Comment by efa2000** [comment]
проблема с установкой/обновлением осталась ?

**Comment by KuzinHouse** [comment]
Пока не знаю. Я в отпуске до конца месяца. 

С уважением,
Дмитрий Милосердов

**Comment by TomasDlg** [comment]
Да проблема с обновлением осталась при обновлении на 0.4.1.

**Comment by TomasDlg** [comment]
2020-07-25T15:43:52.225Z Install : node-red-contrib-alice 0.4.1

2020-07-25T15:43:52.828Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-alice@0.4.1
2020-07-25T15:44:46.420Z [out] 
2020-07-25T15:44:46.420Z [out] > grpc@1.24.2 install /config/node-red/node_modules/grpc
2020-07-25T15:44:46.420Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2020-07-25T15:44:46.420Z [out] 
2020-07-25T15:44:48.292Z [err] node-pre-gyp
2020-07-25T15:44:48.294Z [err]  
2020-07-25T15:44:48.294Z [err] WARN Using request for node-pre-gyp https download 
2020-07-25T15:44:49.056Z [err] node-pre-gyp
2020-07-25T15:44:49.057Z [err]  
2020-07-25T15:44:49.057Z [err] WARN
2020-07-25T15:44:49.058Z [err]  
2020-07-25T15:44:49.058Z [err] Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-linux-arm-musl.tar.gz
2020-07-25T15:44:49.059Z [err]  
2020-07-25T15:44:49.059Z [err] node-pre-gyp
2020-07-25T15:44:49.059Z [err]  
2020-07-25T15:44:49.060Z [err] WARN
2020-07-25T15:44:49.060Z [err]  
2020-07-25T15:44:49.061Z [err] Pre-built binaries not found for grpc@1.24.2 and node@12.17.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
2020-07-25T15:44:49.061Z [err]  
2020-07-25T15:44:54.449Z [err] gyp
2020-07-25T15:44:54.466Z [err]  
2020-07-25T15:44:54.467Z [err] ERR! build error 
2020-07-25T15:44:54.474Z [err] gyp
2020-07-25T15:44:54.474Z [err]  ERR!
2020-07-25T15:44:54.475Z [err]  stack
2020-07-25T15:44:54.475Z [err]  Error: not found: make
2020-07-25T15:44:54.475Z [err] gyp ERR!
2020-07-25T15:44:54.475Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-07-25T15:44:54.475Z [err] gyp 
2020-07-25T15:44:54.476Z [err] ERR! 
2020-07-25T15:44:54.476Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-07-25T15:44:54.476Z [err] gyp
2020-07-25T15:44:54.476Z [err]  ERR! stack
2020-07-25T15:44:54.476Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-07-25T15:44:54.476Z [err] gyp
2020-07-25T15:44:54.477Z [err]  ERR! 
2020-07-25T15:44:54.477Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-07-25T15:44:54.477Z [err] gyp
2020-07-25T15:44:54.477Z [err]  ERR! stack
2020-07-25T15:44:54.477Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-07-25T15:44:54.477Z [err] gyp
2020-07-25T15:44:54.477Z [err]  ERR! 
2020-07-25T15:44:54.478Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-07-25T15:44:54.478Z [err] gyp
2020-07-25T15:44:54.478Z [err]  ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
2020-07-25T15:44:54.479Z [err] gyp
2020-07-25T15:44:54.607Z [err]  ERR! System Linux 4.19.118-v7l+
2020-07-25T15:44:54.618Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-07-25T15:44:54.618Z [err] gyp ERR! cwd /config/node-red/node_modules/grpc
2020-07-25T15:44:54.618Z [err] gyp ERR! node -v v12.17.0
2020-07-25T15:44:54.618Z [err] gyp ERR! node-gyp -v v5.1.0
2020-07-25T15:44:54.618Z [err] gyp ERR! not ok 
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! build error 
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! System Linux 4.19.118-v7l+
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! cwd /config/node-red/node_modules/grpc
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! node -v v12.17.0
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! node-pre-gyp -v v0.14.0
2020-07-25T15:44:54.618Z [err] node-pre-gyp ERR! not ok 
2020-07-25T15:44:54.619Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-25T15:44:56.929Z [err] npm
2020-07-25T15:44:56.929Z [err]  ERR! code ELIFECYCLE
2020-07-25T15:44:56.930Z [err] npm ERR!
2020-07-25T15:44:56.930Z [err]  errno 1
2020-07-25T15:44:56.937Z [err] npm
2020-07-25T15:44:56.938Z [err]  ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2020-07-25T15:44:56.938Z [err] npm ERR!
2020-07-25T15:44:56.938Z [err]  Exit status 1
2020-07-25T15:44:56.938Z [err] npm
2020-07-25T15:44:56.938Z [err]  ERR! 
2020-07-25T15:44:56.938Z [err] npm ERR!
2020-07-25T15:44:56.938Z [err]  Failed at the grpc@1.24.2 install script.
2020-07-25T15:44:56.938Z [err] npm 
2020-07-25T15:44:56.938Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-07-25T15:44:56.991Z [err] 
2020-07-25T15:44:56.991Z [err] npm ERR! A complete log of this run can be found in:
2020-07-25T15:44:56.991Z [err] npm ERR!     /root/.npm/_logs/2020-07-25T15_44_56_963Z-debug.log
2020-07-25T15:44:57.019Z rc=1

**Comment by TomasDlg** [comment]
Частичное решение проблемы для Home Assistant Community Add-on: Node-RED.
В конфигурации указать следующие строки:
`system_packages:
  - make
  - g++
npm_packages:
  - node-pre-gyp
  - grpc`
и перезапустить Add-on.

Но возникает другая проблема - при обновлении node-red-contrib-alice малина (raspberry pi 4) зависает.
Лог при обновлении:
`2020-07-27T17:24:10.076Z Install : node-red-contrib-alice 0.4.1

2020-07-27T17:24:12.040Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-alice@0.4.1
2020-07-27T17:26:04.213Z [out] 
2020-07-27T17:26:04.213Z [out] > grpc@1.24.2 install /config/node-red/node_modules/grpc
2020-07-27T17:26:04.213Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2020-07-27T17:26:04.213Z [out] 
2020-07-27T17:26:06.719Z [err] node-pre-gyp
2020-07-27T17:26:06.721Z [err]  
2020-07-27T17:26:06.721Z [err] WARN Using request for node-pre-gyp https download 
2020-07-27T17:26:07.856Z [err] node-pre-gyp
2020-07-27T17:26:07.858Z [err]  
2020-07-27T17:26:07.859Z [err] WARN
2020-07-27T17:26:07.860Z [err]  
2020-07-27T17:26:07.860Z [err] Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-linux-arm-musl.tar.gz
2020-07-27T17:26:07.861Z [err]  
2020-07-27T17:26:07.862Z [err] node-pre-gyp
2020-07-27T17:26:07.863Z [err]  
2020-07-27T17:26:07.864Z [err] WARN
2020-07-27T17:26:07.864Z [err]  
2020-07-27T17:26:07.865Z [err] Pre-built binaries not found for grpc@1.24.2 and node@12.17.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
2020-07-27T17:26:07.865Z [err]  
2020-07-27T17:26:12.187Z [out] make: Entering directory '/config/node-red/node_modules/grpc/build'
2020-07-27T17:26:12.194Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
2020-07-27T17:26:15.832Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
2020-07-27T17:26:17.075Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
2020-07-27T17:26:18.969Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
2020-07-27T17:26:20.318Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
2020-07-27T17:26:22.303Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
2020-07-27T17:26:24.168Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
2020-07-27T17:26:26.884Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz.o
2020-07-27T17:26:32.717Z [out]   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o`

**Comment by TomasDlg** [comment]
### Главный вопрос вот в чем - Почему до обновления 0.3.13 не требовалось устанавливать дополнительные пакеты (node-pre-gyp, grpc)?

**Comment by TomasDlg** [comment]
Наконец-то получилось обновится.
В конфигурации  Home Assistant Community Add-on: Node-RED указать:
system_packages:
 ```
 - make
  - g++
npm_packages:
  - node-pre-gyp
```
Через portainer остановить все контейнеры кроме: hassio_supervisor, portainer,  addon_a0d7b954_nodered.
И обновится через manager palette.
Время обновления около 20 мин.

**Comment by efa2000** [comment]
Спасибо за найденное решение, плагин тестировался только на чистом NodeRed и не в контейнерах :(
Честно говоря даже не знал, что для HA есть аддон NodeRed

**Comment by efa2000** [comment]
Начиная с версии 0.4.4 моего плагина установлена обновлённая версия firebase, которая уже не требует компиляции 
По идее должно уже обновляться стандартным образом, но про верить к сожалению не могу

**Comment by TomasDlg** [comment]
Добрый день.
В конфигурации Home Assistant Community Add-on: Node-RED убрал все ранее установленные дополнительные пакеты.
И обновился на 0.4.4 без проблем.
