### ISSUE TITLE
Падает node-red при использовании алисы

### ISSUE THREAD

**Issue by krokus57** [efa2000/node-red-contrib-alice#48]
Добрый день.

Периодически падает node-red при подаче команды модулю on_off и всегда падает при подаче на вход модулю on_off обратной связи true/false.
Версия модуля: 0.4.1
Node-RED version: v1.0.6
Node.js  version: v13.5.0
Линукс:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

1. Лог при подаче обратной связи:

```
Sep 16 09:00:40 hpms Node-RED[25164]: 16 Sep 09:00:40 - [info] [alexa-smart-home-v3-conf:XXXXXXXX Свет под навесом : sending state update, topic:state/XXXXX/XXXXXX message:{"messageId":"XXXXXXX","payload":{"state":{"power":"ON"}}}
Sep 16 09:00:53 hpms Node-RED[25164]: 16 Sep 09:00:53 - [red] Uncaught Exception:
Sep 16 09:00:53 hpms Node-RED[25164]: 16 Sep 09:00:53 - TypeError: Cannot read property 'update' of null
Sep 16 09:00:53 hpms Node-RED[25164]: at AliceDevice.<anonymous> (/root/.node-red/node_modules/node-red-contrib-alice/nodes/alice-onoff.js:72:20)
Sep 16 09:00:53 hpms Node-RED[25164]: at AliceDevice.emit (events.js:317:22)
Sep 16 09:00:53 hpms Node-RED[25164]: at AliceDevice.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:185:20)
Sep 16 09:00:53 hpms Node-RED[25164]: at /root/.node-red/node_modules/node-red-contrib-alice/nodes/alice.js:144:18
Sep 16 09:00:53 hpms Node-RED[25164]: at Array.forEach (<anonymous>)
Sep 16 09:00:53 hpms Node-RED[25164]: at Object.next (/root/.node-red/node_modules/node-red-contrib-alice/nodes/alice.js:141:36)
Sep 16 09:00:53 hpms Node-RED[25164]: at next (/root/.node-red/node_modules/@firebase/firestore/dist/index.node.cjs.js:17987:30)
Sep 16 09:00:53 hpms Node-RED[25164]: at Timeout._onTimeout (/root/.node-red/node_modules/@firebase/firestore/dist/index.node.cjs.js:14839:21)
Sep 16 09:00:53 hpms Node-RED[25164]: at listOnTimeout (internal/timers.js:537:17)
Sep 16 09:00:53 hpms Node-RED[25164]: at processTimers (internal/timers.js:481:7)
Sep 16 09:00:53 hpms systemd[1]: Stopping Node-RED graphical event wiring tool...
Sep 16 09:00:53 hpms systemd[1]: Starting Node-RED graphical event wiring tool...
Sep 16 09:00:53 hpms systemd[1]: Started Node-RED graphical event wiring tool.
Sep 16 09:00:54 hpms Node-RED[27819]: 16 Sep 09:00:54 - [info]
Sep 16 09:00:54 hpms Node-RED[27819]: Welcome to Node-RED
Sep 16 09:00:54 hpms Node-RED[27819]: ===================
Sep 16 09:00:54 hpms Node-RED[27819]: 16 Sep 09:00:54 - [info] Node-RED version: v1.0.6
Sep 16 09:00:54 hpms Node-RED[27819]: 16 Sep 09:00:54 - [info] Node.js  version: v13.5.0
Sep 16 09:00:54 hpms Node-RED[27819]: 16 Sep 09:00:54 - [info] Linux 4.4.134-1-pve x64 LE
Sep 16 09:00:55 hpms Node-RED[27819]: 16 Sep 09:00:55 - [info] Loading palette nodes
```

2. Лог при периодическом падении:
```
Sep 16 08:35:34 hpms Node-RED[24758]: 16 Sep 08:35:34 - [info] [alexa-smart-home-v3-conf:_______________] Свет под навесом : sending state update, topic:state/_________________ message:{"messageId":"_________________","payload":{"state":{"power":"OFF"}}}
Sep 16 08:36:01 hpms Node-RED[24758]: 16 Sep 08:36:01 - [info] Stopping modified flows
Sep 16 08:36:01 hpms Node-RED[24758]: 16 Sep 08:36:01 - [info] Stopped modified flows
Sep 16 08:36:01 hpms Node-RED[24758]: 16 Sep 08:36:01 - [info] Starting modified flows
Sep 16 08:36:01 hpms Node-RED[24758]: 16 Sep 08:36:01 - [info] Started modified flows
Sep 16 08:36:13 hpms Node-RED[24758]: 16 Sep 08:36:13 - [info] Stopping modified flows
Sep 16 08:36:13 hpms Node-RED[24758]: 16 Sep 08:36:13 - [info] Stopped modified flows
Sep 16 08:36:13 hpms Node-RED[24758]: 16 Sep 08:36:13 - [info] Starting modified flows
Sep 16 08:36:13 hpms Node-RED[24758]: 16 Sep 08:36:13 - [info] Started modified flows
Sep 16 08:36:27 hpms Node-RED[24758]: 16 Sep 08:36:27 - [red] Uncaught Exception:
Sep 16 08:36:27 hpms Node-RED[24758]: 16 Sep 08:36:27 - TypeError: Cannot read property 'update' of null
Sep 16 08:36:27 hpms Node-RED[24758]: at AliceDevice.<anonymous> (/root/.node-red/node_modules/node-red-contrib-alice/nodes/alice-onoff.js:72:20)
Sep 16 08:36:27 hpms Node-RED[24758]: at AliceDevice.emit (events.js:317:22)
Sep 16 08:36:27 hpms Node-RED[24758]: at AliceDevice.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:185:20)
Sep 16 08:36:27 hpms Node-RED[24758]: at /root/.node-red/node_modules/node-red-contrib-alice/nodes/alice.js:144:18
Sep 16 08:36:27 hpms Node-RED[24758]: at Array.forEach (<anonymous>)
Sep 16 08:36:27 hpms Node-RED[24758]: at Object.next (/root/.node-red/node_modules/node-red-contrib-alice/nodes/alice.js:141:36)
Sep 16 08:36:27 hpms Node-RED[24758]: at next (/root/.node-red/node_modules/@firebase/firestore/dist/index.node.cjs.js:17987:30)
Sep 16 08:36:27 hpms Node-RED[24758]: at Timeout._onTimeout (/root/.node-red/node_modules/@firebase/firestore/dist/index.node.cjs.js:14839:21)
Sep 16 08:36:27 hpms Node-RED[24758]: at listOnTimeout (internal/timers.js:537:17)
Sep 16 08:36:27 hpms Node-RED[24758]: at processTimers (internal/timers.js:481:7)
Sep 16 08:36:27 hpms systemd[1]: Stopping Node-RED graphical event wiring tool...
Sep 16 08:36:27 hpms systemd[1]: Starting Node-RED graphical event wiring tool...
```

**Comment by Vinndimon** [comment]
Похожая ситуация. NodeRed падает при запуске сценария через Алису. В сценарий входит выключение сразу нескольких лампочек. Лог:
```
22 Nov 01:14:21 - TypeError: Cannot read property 'update' of null
    at AliceDevice.<anonymous> (/config/node-red/node_modules/node-red-contrib-alice/nodes/alice-mode.js:87:18)
    at AliceDevice.emit (events.js:315:20)
    at AliceDevice.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:181:20)
    at /config/node-red/node_modules/node-red-contrib-alice/nodes/alice.js:144:18
    at Array.forEach (<anonymous>)
    at Array.<anonymous> (/config/node-red/node_modules/node-red-contrib-alice/nodes/alice.js:141:36)
    at next (/config/node-red/node_modules/@firebase/firestore/src/api/database.ts:2205:60)
    at Timeout._onTimeout (/config/node-red/node_modules/@firebase/firestore/src/util/async_observer.ts:58:11)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-21T22_14_21_609Z-debug.log
```

**Comment by efa2000** [comment]
Должно было поправится в последней версии
